parameters:
#    degi_user.example.class: Degi\Bundle\UserBundle\Example

services:
#    degi_user.example:
#        class: %degi_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
